### ISSUE TITLE
GUI on iOS Safari is higher than `100vh`

### ISSUE THREAD

**Issue by d9beuD** [d9beuD/genealogist#28]
The solution is to set `-webkit-fill-available` value on height.

```css
#app {
  height: 100vh;
  height: -webkit-fill-available;
  ...
}
```
